WebApplication1/Models/bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.bill_detail = new HashSet<bill_detail>();
        }
    
        public int id { get; set; }
        public int id_customer { get; set; }
        public System.DateTime date_order { get; set; }
        public double total { get; set; }
        public double deposit { get; set; }
        public double unpaid { get; set; }
        public string payment_method { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
        public virtual customer customer { get; set; }
    }
}

WebApplication1/Controllers/BillController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.DAO;

namespace WebApplication1.Controllers
{
    public class BillController : Controller
    {
        // GET: Bill
        project2Entities db = new project2Entities();
        public ActionResult Index()
        {
            //var listbill = listAllPaging(page, pagesize);
           var model = from b in db.bills
                        join cus in db.customers
                           on b.id_customer equals cus.id
                           where b.note.Equals("Chưa Giao")
                                       select new BillCusModel()
                                       {
                                           idbill = b.id,
                                           idcus = cus.id,
                                           namecus = cus.name,
                                           address = cus.address,
                                           date = b.date_order,
                                           phone = cus.phone,
                                           price = b.total,
                                           status = b.note
                                       };
            var listbill = model.ToList();
            return View(listbill);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = from b in db.bills
                        join cus in db.customers
                           on b.id_customer equals cus.id
                        where b.id == id
                        select new BillCusModel()
                        {
                            idbill = b.id,
                            idcus = cus.id,
                            namecus = cus.name,
                            address = cus.address,
                            date = b.date_order,
                            phone = cus.phone,
                            price = b.total,
                            status = b.note
                        };
            BillCusModel bi = model.SingleOrDefault();
            if (bi == null)
            {

                return RedirectToAction("Index", "Invalid");
            }           


            return View(bi);
        }
        //public ActionResult BillDetail(int id)
        //{
        //    FoodDAO dao = new FoodDAO();
        //    var listfood = dao.getFoodInBill(id);
        //    var model = from b in db.bills
        //                join cus in db.customers
        //                on b.id_customer equals cus.id
        //                join bd in db.bill_detail
        //                on b.id equals bd.id_bill
        //                where b.id == id
        //                select new BillCusModel()
        //                {
        //                    idbill = b.id,
        //                    idcus = cus.id,
        //                    namecus = cus.name,
        //                    address = cus.address,
        //                    date = b.date_order,
        //                    phone = cus.phone,
        //                    price = b.total,
        //                    status = b.note,
        //                    foodbill = listfood,

        //                };
        //    return View(model.ToList());
        //}
        [HttpPost]
        public ActionResult Edit(BillCusModel bill)
        {
            bill b = db.bills.SingleOrDefault(x => x.id == bill.idbill);



            if (b == null)
            {

                return RedirectToAction("Index", "Invalid");
            }
            var bil = new bill();
            bil.id = bill.idbill;
            bil.id_customer = bill.idcus;
            bil.note = bill.status;
            bil.payment_method = "Tiền Mặt";
            bil.total = bill.price;
            bil.unpaid = 0;
            bil.date_order = bill.date;
            bil.deposit = bill.price;
            BillDAO dao = new BillDAO();
            bool result = dao.Update(bil);
            var cus = new customer();
            cus.id = bill.idcus;
            cus.name = bill.namecus;
            cus.phone = bill.phone;
            cus.address = bill.address;
            cus.gender = "Nam";
            cus.note = "aadddsdsd";
            CustomerDAO cdao = new CustomerDAO();
            bool result2 = cdao.Update(cus);
            if (result == false || result2 == false)
            {
                return RedirectToAction("Index", "Invalid");
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            bill product = db.bills.SingleOrDefault(n => n.id == id);
            db.bills.Remove(product);
            var billdetail = db.bill_detail.Where(n => n.id_bill == id).ToList();
            foreach (var item in billdetail)
            {
                db.bill_detail.Remove(item);
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Bill/Edit.cshtml
@using WebApplication1.Models;
@model BillCusModel
@{
    ViewBag.Title = "Edit Bill";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}

<div class="banner-bottom">
    <div class="container">
        <!-- news-and-events -->
        <div class="row carousel-holder">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <h2>Create Food</h2>
                    <div class="panel-body">
                        @using (Html.BeginForm("Edit", "Bill", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
                    @Html.ValidationSummary(false, "", new { @class = " text-danger" });
                    @Html.HiddenFor(model => model.idbill)
                            @Html.HiddenFor(model=>model.idcus)
                            @Html.HiddenFor(model=>model.date)
                    <div>
                        <label>Name</label>

                        @Html.TextBoxFor(model => model.namecus, new { @class = "form-control", @autofocus = "autofocus", @placeholder = "FullName" })
                        @Html.ValidationMessageFor(model => model.namecus, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        <label>Price</label>
                        @Html.TextBoxFor(model => model.price, new { @class = "form-control", @placeholder = "Price" })
                        @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        <label>Address</label>
                        @Html.TextBoxFor(model => model.address, new { @class = "form-control", @placeholder = "Summary" })
                        @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label>Phone</label>
                        @Html.TextBoxFor(model => model.phone, new { @class = "form-control", @placeholder = "Detail" })
                        @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        <label>Status</label>
                        @Html.TextBoxFor(model => model.status, new { @class = "form-control", @placeholder = "Detail" })
                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <button type="submit" class="btn btn-success">
                        Submit
                    </button>
}
                    </div>
                </div>
            </div>
            <div class="col-md-2">
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- //news-and-events -->
    </div>
</div>

WebApplication1/Views/Bill/Index.cshtml
@using WebApplication1.Models;
@model List<BillCusModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Tên khách hàng</th>
            <th>Số Điện thoại</th>
            <th>Địa Chỉ</th>
            <th>Price</th>
            <th>Date Order</th>
            <th>Note</th>
            <th>Sửa | Xóa|</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach(var item in Model) {
            <tr>
                <td>@item.namecus</td>
                <td>@item.phone</td>
                <td>@item.address</td>
                <td>@item.price.ToString("N0")</td>
                <td>@item.date</td>
                <td>@item.status</td>

                <td>
                    <a href="@Url.Action("Edit","Bill",new {@id = item.idbill })"><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a> |
                    <a href="@Url.Action("Delete","Bill",new {@id = item.idbill })"><i class="fa fa-trash-o fa-2x" aria-hidden="true"></i></a>
                   
                </td>
            </tr>
            }
        }
    </tbody>
</table>
@*<ul class="pagination pagination-lg">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </ul>*@