WebApplication1/Controllers/SearchPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using PagedList;
namespace WebApplication1.Controllers
{
    public class SearchPageController : Controller
    {
        // GET: SearchPage
        project2Entities db = new project2Entities();
        public ActionResult Index(string searchString,int page = 1, int pagesize = 9)
        {
            var listFood = listAllPaging(searchString,page, pagesize);
            ViewBag.SearchString = searchString;
            return View(listFood);
        }
        public IEnumerable<food> listAllPaging(string searchString,int page, int pagesize)
        {
            IQueryable<food> model = db.foods;
            if (!String.IsNullOrEmpty(searchString))
            {
                model = db.foods.Where(x => x.name.Contains(searchString) || x.summary.Contains(searchString));
            }
            return model.OrderByDescending(x=>x.id).ToPagedList(page, pagesize);
        }
    }
}

WebApplication1/Views/SearchPage/Index.cshtml
@using WebApplication1.Models;

@model PagedList.IPagedList<food>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Layout/LayoutUser.cshtml";
}

<div class="page-container">
    <div data-bottom-top="background-position: 50% 50px;" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -50px;" class="page-title page-menu">
        <div class="container">
            <div class="title-wrapper">
                <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(-5px);" data--50-top="transform: translateY(-15px);opacity:0.8;" data--120-top="transform: translateY(-30px);opacity:0;" data-anchor-target=".page-title" class="title">Tìm kiếm món ăn</div>
                <div data-top="opacity:1;" data--120-top="opacity:0;" data-anchor-target=".page-title" class="divider"><span class="line-before"></span><span class="dot"></span><span class="line-after"></span></div>
                <div data-top="transform: translateY(0px);opacity:1;" data--20-top="transform: translateY(5px);" data--50-top="transform: translateY(15px);opacity:0.8;" data--120-top="transform: translateY(30px);opacity:0;" data-anchor-target=".page-title" class="subtitle">The various dishes are waiting for your coming to enjoy its</div>
            </div>
        </div>
    </div>
    <div class="page-content-wrapper">
        <section class="product-sesction-02 padding-top-100 padding-bottom-100">
            <div class="container">
                <div class="swin-sc swin-sc-title style-3">
                    <p class="title"><span>Tìm kiêm món ăn</span></p>
                </div>
                <div class="swin-sc swin-sc-product products-02 carousel-02">
                    @using (Html.BeginForm("Index", "SearchPage", FormMethod.Get))
    {
                <div class="row ">
                    <label class="col-md-6 col-md-offset-3">Nhập tên món,Miêu tả:<input type="text" value="@ViewBag.SearchString" class="form-control" name="searchString"></label>
                    <label class="col-md-6 col-md-offset-3"><button type="submit">Search</button></label>
                </div>
}

                    <div class="products nav-slider margin-top-50">
                        <div class="row slick-padding">
                            @{
        if (Model.Count > 0)
        {
            foreach (var foods in Model)
            {
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <div class="blog-item item swin-transition">
                                <div class="block-img">
                                    <img src="~/assets/images/hinh_mon_an/@foods.image" alt="" class="img img-responsive" style="height:300px;width:300px;">
                                    <div class="block-circle price-wrapper"><span class="price woocommerce-Price-amount amount"><span class="price-symbol">$</span>@foods.price.ToString("N0")</span></div>
                                    <div class="group-btn"><a href="@Url.Action("Index","FoodDetail",new {@id = @foods.id ,@idtype = @foods.id_type})" class="swin-btn btn-link"><i class="@Url.Action("AddItem","Cart",new { @id = @foods.id,@quantity = 1 })"></i></a><a href="javascript:void(0)" class="swin-btn btn-add-to-card"><i class="fa fa-shopping-basket"></i></a></div>
                                </div>
                                <div class="block-content">
                                    <h5 class="title"><a href="@Url.Action("Index","FoodDetail",new {@id = @foods.id ,@idtype = @foods.id_type})">@foods.name</a></h5>
                                    <div class="product-info">
                                        @foods.summary
                                    </div>
                                </div>
                            </div>
                        </div>
                                    }
                                }
                                else
                                {
                                    <div class="alert alert-danger">No Record Is Match</div>
                                }

                            }


                        </div>
                    </div>

                </div>
                <ul class="pagination pagination-lg">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
                </ul>
            </div>
        </section>
    </div>
</div>