WebApplication1/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.DAO;

namespace WebApplication1.Controllers
{
    public class CreateController : BaseController
    {
        // GET: Create
        project2Entities db = new project2Entities();
        public ActionResult Index()
        {
            ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
            ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
            
            return View();
        }
        public ActionResult Create(AddFoodModel product, HttpPostedFileBase imageUpload,int Type,int Menu)
        {
            if(ModelState.IsValid) {
                if (imageUpload == null)
                {
                    ModelState.AddModelError("", "Nhập Hình Ảnh");
                    ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                    ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                    return View("Index");
                }
                else
                {
                    var fileName = Path.GetFileName(imageUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/assets/images/hinh_mon_an/"), fileName);
                    imageUpload.SaveAs(path);
                    product.Image = fileName;
                }
               
                var food = new food();
                food.id_type = Type;
                food.image = product.Image;
                food.name = product.Name;
                food.price = product.Price;
                food.promotion_price = product.ProPrice;
                food.promotion = product.Promotion;
                food.summary = product.Summary;
                food.update_at = DateTime.Now;
                food.unit = product.Unit;
                food.today = 1;
                food.detail = product.Detail;
                FoodDAO dao = new FoodDAO();
                int id = dao.Insert(food);
                var menudetail = new menu_detail();
                menudetail.id_food = id;
                menudetail.id_menu = Menu;
                menudetail.quantity = 1;
                MenuDAO mdao = new MenuDAO();
                bool result = mdao.Insert(menudetail);

                ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                return RedirectToAction("Index", "Admin");
            }
            else
            {

                ModelState.AddModelError("", "Tạo Món Ăn Thất Bại");
                ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                return View("Index");
            }

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            food fo = db.foods.SingleOrDefault(n => n.id == id);
            if (fo == null)
            {
                
                return RedirectToAction("Index","Invalid");
            }
            FoodDAO dao = new FoodDAO();
            var selectedId = dao.getNameMenuById(id);
            var selectedId2 = dao.getNameTypeById(id);
            AddFoodModel af = new AddFoodModel();
            af.Name = fo.name;
            af.Price = fo.price;
            af.ProPrice = fo.promotion_price;
            af.Promotion = fo.promotion;
            af.Image = fo.image;
            af.Detail = fo.detail;
            af.Summary = fo.summary;
            af.Unit = fo.unit;
            ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name", selectedId2);
            ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name", selectedId);

            return View(af);
        }
        [HttpPost]
        public ActionResult Edit(AddFoodModel product, HttpPostedFileBase imageUpload, int Type, int Menu)
        {
            food fo = db.foods.SingleOrDefault(n => n.id == product.Id);
            if (ModelState.IsValid)
            {
                if (imageUpload == null)
                {                               
                        var model = db.foods.SingleOrDefault(x => x.id == product.Id);
                        product.Image = model.image;                   
                }
                else
                {
                    var fileName = Path.GetFileName(imageUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/assets/images/hinh_mon_an/"), fileName);
                    imageUpload.SaveAs(path);
                    product.Image = fileName;
                }

                var food = new food();
                food.id = product.Id;
                food.id_type = Type;
                food.image = product.Image;
                food.name = product.Name;
                food.price = product.Price;
                food.promotion_price = product.ProPrice;
                food.promotion = product.Promotion;
                food.summary = product.Summary;
                food.update_at = DateTime.Now;
                food.unit = product.Unit;
                food.today = 1;
                food.detail = product.Detail;
                FoodDAO dao = new FoodDAO();
                bool result = dao.Update(food, Type, Menu);
                var menudetail = new menu_detail();
                menudetail.id_food = product.Id;
                menudetail.id_menu = Menu;
                menudetail.quantity = 1;
                MenuDAO mdao = new MenuDAO();
                bool result2 = mdao.Update(menudetail,product.Id);
                if (result == false || result2 == false)
                {
                    ModelState.AddModelError("", "Cập Nhật Món Ăn Thất Bại");
                    ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                    ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                    return View("Index");
                }
                ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                return RedirectToAction("Index", "Admin");
            }
            else
            {

                ModelState.AddModelError("", "Cập Nhật Ăn Thất Bại");
                ViewBag.Type = new SelectList(db.food_type.ToList(), "id", "name");
                ViewBag.Menu = new SelectList(db.menus.ToList(), "id", "name");
                return View("Index");
            }

        }
        public ActionResult Delete(int id)
        {
            food product = db.foods.SingleOrDefault(n => n.id == id);
            db.foods.Remove(product);
            var menu = db.menu_detail.Where(n => n.id_food == id).ToList();
            foreach(var item in menu)
            {
                menu_detail de = db.menu_detail.SingleOrDefault(n => n.id_menu == item.id_food);
                db.menu_detail.Remove(de);
            }
            
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }

}

WebApplication1/Views/Create/Edit.cshtml
@model WebApplication1.Models.AddFoodModel

@{
    ViewBag.Title = "Edit Food";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";

    <div class="banner-bottom">
        <div class="container">
            <!-- news-and-events -->
            <div class="row carousel-holder">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <h2>Create Food</h2>
                        <div class="panel-body">
                            @using (Html.BeginForm("Edit", "Create", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                            {
                                @Html.ValidationSummary(false, "", new { @class = " text-danger" });
                                @Html.HiddenFor(model => model.Id)
                                <div>
                                    <label>Name</label>


                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @autofocus = "autofocus", @placeholder = "FullName" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                                <br>
                                <div>
                                    <label>Type</label>

                                    @Html.DropDownList("Type")
                                    @*@Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @placeholder = "Username" })
                                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })*@
                                </div>
                                <br />
                                <div>
                                    <label>Menu</label>
                                    @Html.DropDownList("Menu")
                                    @*@Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })*@
                                </div>
                                <br />
                                <div>
                                    <label>Price</label>
                                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @placeholder = "Price" })
                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                </div>
                                <br>
                                <div>
                                    <label>Promotion Price</label>
                                    @Html.TextBoxFor(model => model.ProPrice, new { @class = "form-control", @placeholder = "Promotion Price" })
                                    @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
                                </div>
                                <br />
                                <div>
                                    <label>Promotion</label>
                                    @Html.TextBoxFor(model => model.Promotion, new { @class = "form-control", @placeholder = "Promotion" })
                                    @Html.ValidationMessageFor(model => model.Promotion, "", new { @class = "text-danger" })
                                </div>
                                <br />
                                <div>
                                    <label>Summary</label>
                                    @Html.TextBoxFor(model => model.Summary, new { @class = "form-control", @placeholder = "Summary" })
                                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    <label>Detail</label>
                                    @Html.TextBoxFor(model => model.Detail, new { @class = "form-control", @placeholder = "Detail" })
                                    @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                                </div>
                                <br>
                                <div>
                                    <label>Unit</label>
                                    @Html.TextBoxFor(model => model.Unit, new { @class = "form-control", @placeholder = "Unit" })
                                    @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
                                </div>
                                <br />

                                <div>
                                    <label>Image</label>
                                    <input type="file" name="imageUpload" onchange="showMyImage(this)" accept="image/*" value="@Model.Image" />
                                    @*<font style="color:red"> @ViewBag.message</font>*@
                                </div>
                                <div>
                                    <img style="width: 200px" id="thumbnil" src="~/assets/images/hinh_mon_an/@Model.Image">
                                </div>
                                <br />
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- //news-and-events -->
        </div>
    </div>}

<script>

    function showMyImage(fileInput) {
        var files = fileInput.files;
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
            var imageType = /image.*/;
            if (!file.type.match(imageType)) {
                continue;
            }
            var img = document.getElementById("thumbnil");
            img.file = file;
            var reader = new FileReader();
            reader.onload = (function (aImg) {
                return function (e) {
                    aImg.src = e.target.result;
                };
            })(img);
            reader.readAsDataURL(file);
        }
    }

</script>

WebApplication1/Views/Create/Index.cshtml
@using WebApplication1.Models;
@model AddFoodModel
@{
    ViewBag.Title = "Add Fodd";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}
<div class="banner-bottom">
    <div class="container">
        <!-- news-and-events -->
        <div class="row carousel-holder">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <h2>Create Food</h2>
                    <div class="panel-body">
                        @using (Html.BeginForm("Create", "Create", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
                    @Html.ValidationSummary(false, "", new { @class = " text-danger" });

                    <div>
                        <label>Name</label>


                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @autofocus = "autofocus", @placeholder = "FullName" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        @Html.LabelFor(model => model.Id_Type);

                        @Html.DropDownList("Type")
                        @*@Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @placeholder = "Username" })
        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })*@
                    </div>
                    <br />
                    <div>
                        @Html.LabelFor(model => model.Id_Menu);
                        @Html.DropDownList("Menu")
                        @*@Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })*@
                    </div>
                    <br />
                    <div>
                        <label>Price</label>
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @placeholder = "Price" })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        <label>Promotion Price</label>
                        @Html.TextBoxFor(model => model.ProPrice, new { @class = "form-control", @placeholder = "Promotion Price" })
                        @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div>
                        <label>Promotion</label>
                        @Html.TextBoxFor(model => model.Promotion, new { @class = "form-control", @placeholder = "Promotion" })
                        @Html.ValidationMessageFor(model => model.Promotion, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div>
                        <label>Summary</label>
                        @Html.TextBoxFor(model => model.Summary, new { @class = "form-control", @placeholder = "Summary" })
                        @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                    </div>
                    <div>
                        <label>Detail</label>
                        @Html.TextBoxFor(model => model.Detail, new { @class = "form-control", @placeholder = "Detail" })
                        @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                    </div>
                    <br>
                    <div>
                        <label>Unit</label>
                        @Html.TextBoxFor(model => model.Unit, new { @class = "form-control", @placeholder = "Unit" })
                        @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
                    </div>
                    <br />

                    <div>
                        <label>Image</label>
                        <input type="file" name="imageUpload" onchange="showMyImage(this)" accept="image/*" />
                        @*<font style="color:red"> @ViewBag.message</font>*@
                    </div>
                    <div>
                        <img style="width: 200px" id="thumbnil">
                    </div>
                    <br />
                    <button type="submit" class="btn btn-success">
                        Submit
                    </button>
}
                    </div>
                </div>
            </div>
            <div class="col-md-2">
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- //news-and-events -->
    </div>
</div>
<script>

function showMyImage(fileInput) {
    var files = fileInput.files;
    for (var i = 0; i < files.length; i++) {
        var file = files[i];
        var imageType = /image.*/;
        if (!file.type.match(imageType)) {
            continue;
        }
        var img=document.getElementById("thumbnil");
        img.file = file;
        var reader = new FileReader();
        reader.onload = (function(aImg) {
            return function(e) {
                aImg.src = e.target.result;
            };
        })(img);
        reader.readAsDataURL(file);
    }
}

</script>