WebApplication1/Controllers/AddTypeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.DAO;
namespace WebApplication1.Controllers
{
    public class AddTypeController : Controller
    {

        // GET: AddType
        project2Entities db = new project2Entities();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FoodTypeModel product, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload == null)
                {
                    ModelState.AddModelError("", "Nhập Hình Ảnh");
                    return View("Index");
                }
                else
                {
                    var fileName = Path.GetFileName(imageUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/assets/images/hinh_loai_mon_an"), fileName);
                    imageUpload.SaveAs(path);
                    product.image = fileName;
                }

                var type = new food_type();
                type.name = product.name;
                type.description = product.description;
                type.image = product.image;
                try
                {
                    db.food_type.Add(type);
                    db.SaveChanges();
                }catch(Exception ex)
                {
                    return RedirectToAction("Index", "Invalid");
                }               
                return RedirectToAction("Edit");
            }
            else
            {

                ModelState.AddModelError("", "Tạo Món Ăn Thất Bại");
                return View("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int page = 1, int pagesize = 6)
        {

            var listtype = listAllPaging(page, pagesize);
            return View(listtype);
        }
        public IEnumerable<food_type> listAllPaging(int page, int pagesize)
        {
            return db.food_type.OrderByDescending(x => x.id).ToPagedList(page, pagesize);
        }
        [HttpGet]
        public ActionResult ViewDetail(int id)
        {

            food_type fo = db.food_type.SingleOrDefault(n => n.id == id);
            if (fo == null)
            {

                return RedirectToAction("Index", "Invalid");
            }
            var type = new FoodTypeModel();
            type.id = fo.id;
            type.name = fo.name;
            type.image = fo.image;
            type.description = fo.description;
            return View(type);
        }
        [HttpPost]
        public ActionResult Edit(FoodTypeModel product, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                if(imageUpload!=null)
                {
                    var fileName = Path.GetFileName(imageUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/assets/images/hinh_loai_mon_an"), fileName);
                    imageUpload.SaveAs(path);
                    product.image = fileName;
                }
                                else
                {
                    var model = db.food_type.SingleOrDefault(x => x.id == product.id);
                    product.image = model.image;
                }
                var type = new food_type();
                type.id = product.id;
                type.name = product.name;
                type.description = product.description;
                type.image = product.image;
                FoodTypeDAO dao = new FoodTypeDAO();
                bool result = dao.Update(type);
                if (result)
                {
                    return RedirectToAction("Edit");
                }
                return View("Edit");
            }
            else
            {

                ModelState.AddModelError("", "Tạo Món Ăn Thất Bại");
                return View("Index");
            }
          
        }
        public ActionResult Delete(int id)
        {
            food_type type = db.food_type.SingleOrDefault(n => n.id == id);
            db.food_type.Remove(type);

            db.SaveChanges();
            return RedirectToAction("Edit");
        }
    }


}

WebApplication1/Views/AddType/Edit.cshtml
@using WebApplication1.Models;
@model PagedList.IPagedList<food_type>
@using PagedList.Mvc;
@{
    ViewBag.Title = "List Type";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Tên</th>
            <th>Hình</th>
            <th>Summary</th>

            <th>Sửa | Xóa</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr class="@item.id">
                    <td>@item.name</td>
                    <td><img src="~/assets/images/hinh_loai_mon_an/@item.image" style="width: 100px"></td>
                    <td style="width : 200px;">@item.description</td>
                    <td>
                        <a href="@Url.Action("ViewDetail","AddType",new {@id = item.id })"><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a> |
                        <a href="@Url.Action("Delete","AddType",new {@id = item.id })"><i class="fa fa-trash-o fa-2x" aria-hidden="true"></i></a>
                    </td>
                </tr>
            }



        }
    </tbody>
</table>
<ul class="pagination pagination-lg">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</ul>

WebApplication1/Views/AddType/Index.cshtml
@{
    ViewBag.Title = "Add Type";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}

@using WebApplication1.Models;
@model FoodTypeModel

<div class="banner-bottom">
    <div class="container">
        <!-- news-and-events -->
        <div class="row carousel-holder">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <h2>Create Type</h2>
                    <div class="panel-body">
                        @using (Html.BeginForm("Create", "AddType", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.ValidationSummary(false, "", new { @class = " text-danger" });

                            <div>
                                <label>Name</label>


                                @Html.TextBoxFor(model => model.name, new { @class = "form-control", @autofocus = "autofocus", @placeholder = "FullName" })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                            <br />
                            <div>
                                <label>Description</label>
                                @Html.TextBoxFor(model => model.description, new { @class = "form-control", @placeholder = "Summary" })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                            <div>
                                <label>Image</label>
                                <input type="file" name="imageUpload" onchange="showMyImage(this)" accept="image/*" />
                                @*<font style="color:red"> @ViewBag.message</font>*@
                            </div>
                            <div>
                                <img style="width: 200px" id="thumbnil">
                            </div>
                            <br />
                            <button type="submit" class="btn btn-success">
                                Submit
                            </button>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-2">
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- //news-and-events -->
    </div>
</div>
<script>

function showMyImage(fileInput) {
    var files = fileInput.files;
    for (var i = 0; i < files.length; i++) {
        var file = files[i];
        var imageType = /image.*/;
        if (!file.type.match(imageType)) {
            continue;
        }
        var img=document.getElementById("thumbnil");
        img.file = file;
        var reader = new FileReader();
        reader.onload = (function(aImg) {
            return function(e) {
                aImg.src = e.target.result;
            };
        })(img);
        reader.readAsDataURL(file);
    }
}

</script>

WebApplication1/Views/AddType/ViewDetail.cshtml
@{
    ViewBag.Title = "Edit Type";
    Layout = "~/Views/Layout/LayoutAdmin.cshtml";
}

@using WebApplication1.Models;
@model FoodTypeModel

<div class="banner-bottom">
    <div class="container">
        <!-- news-and-events -->
        <div class="row carousel-holder">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <h2>Create Type</h2>
                    <div class="panel-body">
                        @using (Html.BeginForm("Edit", "AddType", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.ValidationSummary(false, "", new { @class = " text-danger" });
                            @Html.HiddenFor(model=>model.id)
                            <div>
                                <label>Name</label>


                                @Html.TextBoxFor(model => model.name, new { @class = "form-control", @autofocus = "autofocus", @placeholder = "FullName" })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                            <br />
                            <div>
                                <label>Description</label>
                                @Html.TextBoxFor(model => model.description, new { @class = "form-control", @placeholder = "Summary" })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                            <div>
                                <label>Image</label>
                                <input type="file" name="imageUpload" onchange="showMyImage(this)" accept="image/*" />
                                @*<font style="color:red"> @ViewBag.message</font>*@
                            </div>
                            <div>
                                <img style="width: 200px" id="thumbnil" src="~/assets/images/hinh_loai_mon_an/@Model.image" />
                            </div>
                            <br />
                            <button type="submit" class="btn btn-success">
                                Submit
                            </button>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-2">
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- //news-and-events -->
    </div>
</div>
<script>

function showMyImage(fileInput) {
    var files = fileInput.files;
    for (var i = 0; i < files.length; i++) {
        var file = files[i];
        var imageType = /image.*/;
        if (!file.type.match(imageType)) {
            continue;
        }
        var img=document.getElementById("thumbnil");
        img.file = file;
        var reader = new FileReader();
        reader.onload = (function(aImg) {
            return function(e) {
                aImg.src = e.target.result;
            };
        })(img);
        reader.readAsDataURL(file);
    }
}

</script>